---

- name: restart virtual machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true
  when: updatepackages.changed

- name: wait for server to restart
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 25
    timeout: 200
  delegate_to: 127.0.0.1
  when: updatepackages.changed
