---

- name: Clone swagger-ui
  git:
    repo: https://github.com/swagger-api/swagger-ui
    dest: "{{path_to_swagger_ui}}"
    update: yes

- name: modify swagger-ui index.html
  lineinfile:
    dest: "{{path_to_swagger_ui}}/dist/index.html"
    regexp: 'url:'
    line: 'url: "https://{{gpte_env}}.opentlc.com/swagger/swagger.yaml",'
