---

- name: Clone swagger-ui
  git:
    repo: https://github.com/swagger-api/swagger-ui
    dest: "{{path_to_swagger_ui}}"
    update: yes
  become: yes
  become_user: "{{user}}"

- name: modify swagger-ui index.html
  lineinfile:
    path: "{{path_to_swagger_ui}}/dist/index.html
    regexp: 'url:'
    line: 'https://{{gpte_env}}.opentlc.com/swagger/swagger.yaml
