---

- name: create lms_reporting database and corresponding user
  mysql_db:
    name: "{{ lms_reporting_db_name }}"
    state: present
- mysql_user:
    name: "{{lms_reporting_userId}}"
    password: "{{lms_reporting_passwd}}"
    priv: '{{ lms_reporting_db_name }}.*:ALL'
    state: present
- mysql_user:
    name: "{{lms_reporting_userId}}"
    password: "{{lms_reporting_passwd}}"
    priv: '{{ lms_reporting_db_name }}.*:ALL'
    state: present
    host: "%"

- name: create dashbuilder database and corresponding user
  mysql_db:
    name: "{{ dashbuilder_db_name }}"
    state: present
- mysql_user:
    name: "{{dashbuilder_db_userId}}"
    password: "{{dashbuilder_db_passwd}}"
    priv: 'dashbuilder.*:ALL'
    state: present
- mysql_user:
    name: "{{dashbuilder_db_userId}}"
    password: "{{dashbuilder_db_passwd}}"
    priv: 'dashbuilder.*:ALL'
    state: present
    host: "%"

- name: create lms_trans database and corresponding user
  mysql_db:
    name: "{{ lms_trans_db_name }}"
    state: present
- mysql_user:
    name: "{{lms_trans_userId}}"
    password: "{{lms_trans_passwd}}"
    priv: '{{ lms_trans_db_name }}.*:ALL'
    state: present
- mysql_user:
    name: "{{lms_trans_userId}}"
    password: "{{lms_trans_passwd}}"
    priv: '{{ lms_trans_db_name }}.*:ALL'
    state: present
    host: "%"

- name: Support RHT data lake foks
  blockinfile:
    dest: "/etc/my.cnf"
    block: |
      # JA Bride:  Added to support RHT data lake folks
      skip-name-resolve


# ############     Seed new environment databases from latest from prod     #######################

- name: Create Backups folder on prod
  file: path={{ src_dump_dir }} state=directory
  run_once: true
  delegate_to: reporting.opentlc.com

- name: Dump remote prod databases
  mysql_db:
    login_user: root
    login_host: localhost
    login_password: "{{ db_root_passwd }}"
    name: "{{ item }}"
    state: dump
    target: "{{ src_dump_dir }}/{{ item }}Db.sql.gz"
  with_items: "{{databases_to_provision_from_prod}}"
  delegate_to: reporting.opentlc.com

- name: Create following directory from which to put fetched database zips; local:{{target_bk_dir}}
  command: mkdir -p {{ target_bk_dir }}
  delegate_to: localhost

- name: Copy database dump files from prod to local:{{target_bk_dir}}
  fetch:
    src: "{{ src_dump_dir }}/{{ item }}Db.sql.gz"
    dest: "{{ target_bk_dir }}"
    flat: yes
  with_items: "{{databases_to_provision_from_prod}}"
  delegate_to: reporting.opentlc.com

- name: Create Backups folder on remote {{gpte_env}} environment
  file: path={{ target_bk_dir }} state=directory

- name: push database dump files from local to remote {{gpte_env}} environment
  copy:
    src: "{{ target_bk_dir }}/{{ item }}Db.sql.gz"
    dest: "{{ target_bk_dir }}"
  with_items: "{{databases_to_provision_from_prod}}"

- name: import data into {{gpte_env}} RDBMS
  mysql_db:
    name: "{{ item }}"
    state: import
    target: "{{ target_bk_dir }}/{{ item }}Db.sql.gz"
  with_items: "{{databases_to_provision_from_prod}}"
