/**
 * This class is generated by jOOQ
 */
package com.redhat.gpe.domain.canonical;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Course implements Serializable {

    private static final long serialVersionUID = 1857558423;

    public static final String COURSE_ID = "CourseID";
    public static final String COURSE_NAME = "CourseName";
    public static final String WHERE_CLAUSE = "c.CourseID,c.CourseName";

    private String courseid;
    private String coursename;

    public Course() {}

    public Course(Course value) {
        this.courseid = value.courseid;
        this.coursename = value.coursename;
    }

    public Course(
        String courseid,
        String coursename
    ) {
        this.courseid = courseid;
        this.coursename = coursename;
    }

    public String getCourseid() {
        return this.courseid;
    }

    public void setCourseid(String courseid) {
        this.courseid = courseid;
    }

    public String getCoursename() {
        return this.coursename;
    }

    public void setCoursename(String coursename) {
        this.coursename = coursename;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Courses (");

        sb.append(courseid);
        sb.append(", ").append(coursename);

        sb.append(")");
        return sb.toString();
    }
}
