/**
 * This class is generated by jOOQ
 */
package com.redhat.gpe.domain.canonical;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CourseMapping implements Serializable {

    private static final long serialVersionUID = 391429063;

    private String newcoursecode;
    private String courseid;
    private String source;

    public CourseMapping() {}

    public CourseMapping(CourseMapping value) {
        this.newcoursecode = value.newcoursecode;
        this.courseid = value.courseid;
        this.source = value.source;
    }

    public CourseMapping(
        String newcoursecode,
        String courseid,
        String source
    ) {
        this.newcoursecode = newcoursecode;
        this.courseid = courseid;
        this.source = source;
    }

    public String getNewcoursecode() {
        return this.newcoursecode;
    }

    public void setNewcoursecode(String newcoursecode) {
        this.newcoursecode = newcoursecode;
    }

    public String getCourseid() {
        return this.courseid;
    }

    public void setCourseid(String courseid) {
        this.courseid = courseid;
    }

    public String getSource() {
        return this.source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Coursemappings (");

        sb.append(", ").append(newcoursecode);
        sb.append(", ").append(courseid);
        sb.append(", ").append(source);

        sb.append(")");
        return sb.toString();
    }
}
