---

- name: Create jboss user's .ssh directory
  file: state=directory path=/home/{{user}}/.ssh owner={{user}} group={{group}} mode=0700

- name: Add ssh config
  template:
    src: config
    dest: /home/{{user}}/.ssh
    mode: "0600"
    owner: "{{user}}"
    group: "{{group}}"

- name: Add id_ecdsa private ssh key
  copy: dest=/home/{{user}}/.ssh owner={{user}} group={{group}} mode=0600 src=id_ecdsa

- name: Clone GPTE Reporting as the jboss user using opentlc-user github account
  git: 
    repo: git@github.com:redhat-gpe/OPEN_Reporting.git
    dest: "{{gpte_reporting_home}}"
    clone: yes 
    accept_hostkey: true 
    key_file: /home/{{user}}/.ssh/id_ecdsa
  become: yes
  become_user: "{{user}}"

