<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.4.15.5 setup script
 * Date: Wed, 23 Mar 2016 03:06:10 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: phpHost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'localhost';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '{{db_root_passwd}}';

/* End of servers configuration */

$cfg['blowfish_secret'] = '56f206f81ddce1.18937795';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
