package com.redhat.gpe.accreditation.rules;

dialect "mvel"

import java.util.Date
import java.util.ArrayList
import com.redhat.gpe.domain.canonical.Student
import com.redhat.gpe.domain.canonical.StudentAccreditation
import com.redhat.gpe.domain.helper.CourseCompletion
import com.redhat.gpe.domain.helper.Accreditation
import com.redhat.gpte.util.DroolsCommandHelper

global ArrayList accreditationList



rule "4_Red Hat Delivery Specialist - Advanced Cloud Infrastructure_with_7_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 8 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 8 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Red Hat Ceph Storage for OpenStack")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "OpenStack Director")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, name == "OpenStack Advanced Storage")
    $cc6:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, name == "OpenStack Advanced Networking")
    $cc7:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, this != $cc6, name == "Advanced Cloud Infrastructure Project Hours")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Sep-2016", "", $cc1, $cc2, $cc3, $cc4, $cc5, $cc6, $cc7 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5, $cc6, $cc7 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Cloud Infrastructure");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "5_Red Hat Delivery Specialist - Advanced Cloud Infrastructure_with_7_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 10 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 10 Concepts and Architecture")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "OpenStack 10 Director")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "Red Hat Ceph Storage 2 for OpenStack 10")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, name == "OpenStack Advanced Storage")
    $cc6:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, name == "OpenStack Advanced Networking")
    $cc7:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, this != $cc6, name == "Advanced Cloud Infrastructure Project Hours")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2017", "", $cc1, $cc2, $cc3, $cc4, $cc5, $cc6, $cc7 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5, $cc6, $cc7 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Cloud Infrastructure");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "6_Red Hat Delivery Specialist - Advanced Cloud Infrastructure_with_7_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 10 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 10 Concepts and Architecture")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "OpenStack 10 Director")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "Red Hat Ceph Storage 2 for OpenStack 10")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, name == "OpenStack Advanced Storage")
    $cc6:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, name == "OpenStack Advanced Networking")
    $cc7:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, this != $cc6, name == "Advanced OpenStack Director")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2017", "", $cc1, $cc2, $cc3, $cc4, $cc5, $cc6, $cc7 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5, $cc6, $cc7 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Cloud Infrastructure");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "7_Red Hat Sales Engineer Specialist - Cloud Management_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "CloudForms FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2014", "1-Jul-2014", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Engineer Specialist - Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "8_Red Hat Sales Engineer Specialist - Platform as a Service_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenShift Administration")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2014", "1-Jul-2014", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Engineer Specialist - Platform as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "9_Red Hat Sales Engineer Specialist - Infrastructure as a Service_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 6 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2014", "1-Apr-2015", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Engineer Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "10_Red Hat Sales Specialist - Infrastructure as a Service_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Infrastructure-as-a-Service Essentials for Salespe")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jun-2014", "1-May-2015", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "11_Red Hat Delivery Specialist - Advanced Cloud Management_with_6_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "CloudForms 4 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "CloudForms 4 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Red Hat Satellite 6 Implementation")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "CloudForms 4 Customization and Automation")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, name == "Red Hat Cloud Suite Foundations")
    $cc6:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, name == "Advanced Cloud Management Project Hours")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Sep-2016", "", $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "12_Red Hat Delivery Specialist - Advanced Cloud Management_with_5_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "CloudForms 4 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "CloudForms 4 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Red Hat Satellite 6 Implementation")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "CloudForms 4 Customization and Automation")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, name == "Advanced Cloud Management Project Hours")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2017", "", $cc1, $cc2, $cc3, $cc4, $cc5 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "13_Red Hat Delivery Specialist - Platform as a Service_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenShift Administration")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2014", "1-Aug-2015", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Platform as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "14_Red Hat Sales Engineer Specialist - Platform as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Platform-as-a-Service (PaaS) Solution for Sales")
    $cc2:CourseCompletion(this != $cc1, name == "OpenShift Administration")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jul-2014", "1-Aug-2015", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Engineer Specialist - Platform as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "15_Red Hat Delivery Specialist - Advanced OpenStack Networking_with_5_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 10 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 10 Concepts and Architecture")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "OpenStack 10 Director")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "Red Hat Ceph Storage 2 for OpenStack 10")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, name == "OpenStack Advanced Networking")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2017", "", $cc1, $cc2, $cc3, $cc4, $cc5 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced OpenStack Networking");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "16_Red Hat Delivery Specialist - Advanced OpenStack Storage_with_5_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 10 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 10 Concepts and Architecture")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "OpenStack 10 Director")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "Red Hat Ceph Storage 2 for OpenStack 10")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, name == "OpenStack Advanced Storage")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2017", "", $cc1, $cc2, $cc3, $cc4, $cc5 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced OpenStack Storage");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "17_Red Hat Delivery Specialist - Advanced Platform as a Service_with_6_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenShift 3 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "OpenShift 3 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Application Development with OpenShift")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "Advanced OpenShift Development")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, name == "Advanced OpenShift Deployment")
    $cc6:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, name == "Advanced PaaS Project Hours")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Apr-2017", "", $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Platform as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "18_Red Hat Delivery Specialist - Infrastructure as a Service_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 6 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2014", "1-Sep-2015", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "19_Red Hat Sales Engineer Specialist - Infrastructure as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "IaaS Solution for Sales Engineer")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 6 FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Apr-2015", "1-Oct-2015", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Engineer Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "20_Red Hat Sales Specialist - Infrastructure as a Service_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "IaaS Solutions for Salesperson")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-May-2015", "1-Oct-2015", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "21_Red Hat Delivery Specialist - Advanced Cloud Management_with_3_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "CloudForms FASTRAX")
    $cc2:CourseCompletion(this != $cc1, name == "CloudForms Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "CloudForms Customization and Automation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jun-2014", "1-Mar-2016", $cc1, $cc2, $cc3))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "22_Red Hat Delivery Specialist - Advanced Platform as a Service Deployment_with_4_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenShift 3 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "OpenShift 3 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Advanced OpenShift Deployment")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "Advanced PaaS Project Hours")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Apr-2017", "", $cc1, $cc2, $cc3, $cc4 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Platform as a Service Deployment");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "23_Red Hat Delivery Specialist - Advanced Platform as a Service Development_with_4_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenShift 3 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "Application Development with OpenShift")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Advanced OpenShift Development")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "Advanced PaaS Project Hours")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Apr-2017", "", $cc1, $cc2, $cc3, $cc4 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Platform as a Service Development");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "24_Red Hat Delivery Specialist - Infrastructure as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 6 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 6 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Sep-2015", "1-May-2016", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "25_Red Hat Delivery Specialist - Cloud Automation_with_3_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Ansible Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "Ansible Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Ansible Tower Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "26-May-2017", "", $cc1, $cc2, $cc3))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Cloud Automation");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "26_Red Hat Delivery Specialist - Cloud Automation_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Ansible Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "Ansible Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "26-May-2017", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Cloud Automation");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "27_Red Hat Sales Engineer Specialist - Infrastructure as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Red Hat OpenStack Platform for Sales")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 6 FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Oct-2015", "1-May-2016", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Engineer Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "28_Red Hat Delivery Specialist - Cloud Management_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "CloudForms 4 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "CloudForms 4 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2016", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "29_Red Hat Delivery Specialist - Advanced Cloud Infrastructure_with_6_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 7 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 7 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Red Hat Ceph Storage for OpenStack")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "OpenStack Director")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, name == "OpenStack Advanced Storage")
    $cc6:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, name == "OpenStack Advanced Networking")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2016", "1-Jul-2016", $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Cloud Infrastructure");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "30_Red Hat Delivery Specialist - Infrastructure as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 7 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 8 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2016", "1-Jul-2016", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "31_Red Hat Sales Engineer Specialist - Cloud Management_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Cloud Management Solution for Salesperson")
    $cc2:CourseCompletion(this != $cc1, name == "CloudForms FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jul-2014", "1-Aug-2016", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Engineer Specialist - Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "32_Red Hat Delivery Specialist - Advanced Cloud Infrastructure_with_6_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 8 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 8 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Red Hat Ceph Storage for OpenStack")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "OpenStack Director")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, name == "OpenStack Advanced Storage")
    $cc6:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, name == "OpenStack Advanced Networking")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2016", "1-Sep-2016", $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Cloud Infrastructure");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "33_Red Hat Delivery Specialist - Infrastructure as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 8 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 8 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2016", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "34_Red Hat Delivery Specialist - Infrastructure as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 8 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 10 Concepts and Architecture")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "10-Jul-2017", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "35_Red Hat Delivery Specialist - Infrastructure as a Service_with_3_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 10 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 10 Concepts and Architecture")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "OpenStack 10 Director")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Aug-2017", "", $cc1, $cc2, $cc3))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "36_Red Hat Delivery Specialist - PaaS Development_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenShift 3 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "Application Development with OpenShift")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2016", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - PaaS Development");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "37_Red Hat Delivery Specialist - Advanced Cloud Infrastructure_with_7_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 7 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 8 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Red Hat Ceph Storage for OpenStack")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "OpenStack Director")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, name == "OpenStack Advanced Storage")
    $cc6:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, name == "OpenStack Advanced Networking")
    $cc7:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, this != $cc6, name == "Advanced Cloud Infrastructure Project Hours")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jul-2016", "1-Sep-2016", $cc1, $cc2, $cc3, $cc4, $cc5, $cc6, $cc7 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5, $cc6, $cc7 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Cloud Infrastructure");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "38_Red Hat Delivery Specialist - Platform as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenShift 3 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "OpenShift 3 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-May-2015", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Platform as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "39_Red Hat Delivery Specialist - Advanced Cloud Management_with_5_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "CloudForms 4 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "CloudForms 4 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Red Hat Satellite 6 Implementation")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "CloudForms Customization and Automation")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, name == "Red Hat Cloud Suite Foundations")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2016", "1-Sep-2016", $cc1, $cc2, $cc3, $cc4, $cc5 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "40_Red Hat Delivery Specialist - Red Hat Ceph Storage for OpenStack_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Red Hat Ceph Storage 2 for OpenStack 10")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Dec-2016", "1-Sep-2017", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Red Hat Ceph Storage for OpenStack");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "41_Red Hat Sales Engineer Specialist - Cloud Automation_with_3_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Ansible Tower Sales")
    $cc2:CourseCompletion(this != $cc1, name == "Ansible Foundations")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Ansible Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "26-May-2017", "", $cc1, $cc2, $cc3))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Engineer Specialist - Cloud Automation");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "42_Red Hat Delivery Specialist - Advanced Cloud Management_with_5_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "CloudForms 4 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "CloudForms 4 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Red Hat Satellite 6 Implementation")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "CloudForms 4 Customization and Automation")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, name == "Red Hat Cloud Suite Foundations")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2016", "1-Sep-2016", $cc1, $cc2, $cc3, $cc4, $cc5 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "43_Red Hat Delivery Specialist - Advanced Platform as a Service_with_4_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenShift 3 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "OpenShift 3 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Application Development with OpenShift")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "Advanced OpenShift")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2016", "1-Sep-2016", $cc1, $cc2, $cc3, $cc4 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Platform as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "44_Red Hat Delivery Specialist - Advanced Platform as a Service_with_5_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenShift 3 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "OpenShift 3 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Application Development with OpenShift")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "Advanced OpenShift")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, name == "Advanced PaaS Project Hours")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Sep-2016", "1-May-2017", $cc1, $cc2, $cc3, $cc4, $cc5 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Platform as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "45_Red Hat Sales Engineer Specialist - Cloud Management_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Cloud Management Solution for Salesperson")
    $cc2:CourseCompletion(this != $cc1, name == "CloudForms 4 Foundations")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2016", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Engineer Specialist - Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "46_Red Hat Delivery Specialist - Advanced Platform as a Service_with_5_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenShift 3 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "OpenShift 3 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Application Development with OpenShift")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "Advanced OpenShift")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, name == "Advanced PaaS Project Hours")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Sep-2016", "1-May-2017", $cc1, $cc2, $cc3, $cc4, $cc5 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Platform as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "47_Red Hat Delivery Specialist - Advanced Platform as a Service_with_5_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenShift 3 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "OpenShift 3 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, name == "Application Development with OpenShift")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, name == "Advanced OpenShift Deployment")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, name == "Advanced PaaS Project Hours")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Nov-2016", "1-May-2017", $cc1, $cc2, $cc3, $cc4, $cc5 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5 );

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Advanced Platform as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "48_Red Hat Delivery Specialist - Cloud Management_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "CloudForms FASTRAX")
    $cc2:CourseCompletion(this != $cc1, name == "CloudForms Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2014", "1-May-2017", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "49_Red Hat Sales Engineer Specialist - Infrastructure as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Red Hat OpenStack Platform for Sales")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 7 FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Nov-2015", "1-May-2017", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Engineer Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "50_Red Hat Sales Engineer Specialist - Infrastructure as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Red Hat OpenStack Platform for Sales")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 8 FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2016", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Engineer Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "51_Red Hat Sales Engineer Specialist - Infrastructure as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 10 Foundations")
    $cc2:CourseCompletion(this != $cc1, name == "Red Hat OpenStack Platform for Sales")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Aug-2017", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Engineer Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "52_Red Hat Delivery Specialist - Infrastructure as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "OpenStack 7 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, name == "OpenStack 7 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Nov-2015", "1-May-2017", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "53_Red Hat Sales Engineer Specialist - Cloud Automation_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Ansible Tower Sales")
    $cc2:CourseCompletion(this != $cc1, name == "Ansible Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jul-2016", "26-May-2017", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Engineer Specialist - Cloud Automation");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "54_Red Hat Sales Engineer Specialist - Platform as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Platform-as-a-Service (PaaS) Solution for Sales")
    $cc2:CourseCompletion(this != $cc1, name == "OpenShift 3 Foundations")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jun-2015", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Engineer Specialist - Platform as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "55_Red Hat Sales Engineer Specialist - Red Hat Cloud Suite_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Red Hat Cloud Suite Foundations")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2016", "1-Sep-2017", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Engineer Specialist - Red Hat Cloud Suite");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "56_Red Hat Sales Specialist - Cloud Automation_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Ansible Tower Sales")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-May-2016", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Specialist - Cloud Automation");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "57_Red Hat Sales Specialist - Cloud Management_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Cloud Management Solution for Salesperson")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jul-2014", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Specialist - Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "58_Red Hat Sales Specialist - How to sell Red Hat Cloud Suite_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Red Hat Cloud Suite Sales")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-May-2016", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Specialist - How to sell Red Hat Cloud Suite");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "59_Red Hat Delivery Specialist - Red Hat Ceph Storage for OpenStack_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Red Hat Ceph Storage for OpenStack")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2016", "10-Jul-2017", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Red Hat Ceph Storage for OpenStack");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "60_Red Hat Delivery Specialist - Cloud Automation_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Ansible Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jul-2016", "1-Aug-2017", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Delivery Specialist - Cloud Automation");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "61_Red Hat Sales Specialist - Infrastructure as a Service_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Red Hat OpenStack Platform for Sales")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Oct-2015", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "62_Red Hat Sales Specialist - Platform as a Service_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Platform-as-a-Service (PaaS) Solution for Sales")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jul-2014", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Specialist - Platform as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end
