package com.redhat.gpe.accreditation.rules;

dialect "mvel"

import java.util.Date
import java.util.ArrayList
import com.redhat.gpe.domain.canonical.Student
import com.redhat.gpe.domain.canonical.StudentAccreditation
import com.redhat.gpe.domain.helper.CourseCompletion
import com.redhat.gpe.domain.helper.Accreditation
import com.redhat.gpte.util.DroolsCommandHelper

global ArrayList accreditationList



rule "4_Red Hat Sales Specialist - IT Optimization_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "IT Optimization Conversation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2019", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Specialist - IT Optimization");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "5_Red Hat Sales Specialist - Cloud-Native Application Development_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Cloud-Native App Dev Conversation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2019", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Specialist - Cloud-Native Application Development");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "6_Red Hat Sales Specialist - Agile Integration_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Agile Integration Conversation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2019", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Specialist - Agile Integration");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "7_Red Hat Sales Specialist - Hybrid Cloud Infrastructure_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "Hybrid Cloud Infrastructure Conversation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2019", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Specialist - Hybrid Cloud Infrastructure");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "8_Red Hat Sales Specialist - IT Automation and Management_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(name == "IT Automation and Management Conversation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2019", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setName("Red Hat Sales Specialist - IT Automation and Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getName());
    accreditation.setCompletionDate(latestCC.getCompletionDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end
