package com.redhat.gpe.accreditation.rules;

dialect "mvel"

import java.util.Date
import java.util.ArrayList
import com.redhat.gpe.domain.canonical.Student
import com.redhat.gpe.domain.canonical.StudentAccreditation
import com.redhat.gpe.domain.helper.CourseCompletion
import com.redhat.gpe.domain.helper.Accreditation
import com.redhat.gpte.util.DroolsCommandHelper

global ArrayList accreditationList



rule "4_Red Hat Delivery Specialist - Red Hat Enterprise Linux (7) Troubleshooting_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Enterprise Linux 7 Troubleshooting")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jun-2015", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Red Hat Enterprise Linux (7) Troubleshooting");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "5_Red Hat Delivery Specialist - Platform_with_5_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Corebuild Accelerator")
    $cc2:CourseCompletion(this != $cc1, courseName == "Satellite Accelerator")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "RHEL (6) Implementation")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "Satellite (5) FASTRAX")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, courseName == "RHEL (6) Troubleshooting")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jun-2013", "1-Jul-2014", $cc1, $cc2, $cc3, $cc4, $cc5 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "6_Red Hat Delivery Specialist - Platform_with_3_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "RHEL (6) Implementation")
    $cc2:CourseCompletion(this != $cc1, courseName == "Satellite (5) FASTRAX")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "RHEL (6) Troubleshooting")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jul-2014", "1-May-2015", $cc1, $cc2, $cc3))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "7_Red Hat Delivery Specialist - Platform_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Enterprise Linux 7 Implementation")
    $cc2:CourseCompletion(this != $cc1, courseName == "Satellite (5) FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2015", "1-Aug-2015", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "8_Red Hat Delivery Specialist - Platform_with_3_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "RHEL (6) Implementation")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat Satellite 6 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "RHEL (6) Troubleshooting")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2015", "1-May-2015", $cc1, $cc2, $cc3))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "9_Red Hat Delivery Specialist - Platform_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Enterprise Linux 7 Implementation")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat Satellite 6 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2015", "1-Aug-2015", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "10_Red Hat Delivery Specialist - Platform_with_3_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Enterprise Linux 7 Implementation")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat Satellite 6 FASTRAX")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "Red Hat Satellite 6 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Aug-2015", "", $cc1, $cc2, $cc3))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "11_Red Hat Delivery Specialist - RHEL for SAP HANA_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Enterprise Linux for SAP Hana")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Apr-2015", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - RHEL for SAP HANA");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "12_Red Hat Delivery Specialist - Storage_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Gluster Storage 3 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Aug-2013", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Storage");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "13_Red Hat Delivery Specialist - Virtualization_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "RHEV Accelerator")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat Enterprise Virtualization FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2013", "1-Aug-2013", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Virtualization");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "14_Red Hat Delivery Specialist - Virtualization_with_3_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "RHEV Accelerator")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat Enterprise Virtualization FASTRAX")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "Red Hat Enterprise Virtualization Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Aug-2013", "1-Jul-2014", $cc1, $cc2, $cc3))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Virtualization");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "15_Red Hat Delivery Specialist - Virtualization_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Enterprise Virtualization FASTRAX")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat Enterprise Virtualization Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jul-2014", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Virtualization");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "16_Red Hat Sales Engineer Specialist - Platform_with_7_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform Solutions for PreSales")
    $cc2:CourseCompletion(this != $cc1, courseName == "RHEL 6 Sales Essentials Level 2")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "RHEL 6 Sales Essentials Add-ons")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "RHN Satellite Sales")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, courseName == "RHEL (6) Implementation")
    $cc6:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, courseName == "Satellite (5) FASTRAX")
    $cc7:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, this != $cc6, courseName == "RHEL (6) Troubleshooting")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jun-2013", "1-Aug-2015", $cc1, $cc2, $cc3, $cc4, $cc5, $cc6, $cc7 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5, $cc6, $cc7 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "17_Red Hat Sales Engineer Specialist - Platform_with_5_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform Essentials for Red Hat Technical Sales Partners")
    $cc2:CourseCompletion(this != $cc1, courseName == "RHN Satellite Sales")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "RHEL (6) Implementation")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "Satellite (5) FASTRAX")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, courseName == "RHEL (6) Troubleshooting")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jul-2014", "1-Aug-2015", $cc1, $cc2, $cc3, $cc4, $cc5 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "18_Red Hat Sales Engineer Specialist - Platform_with_4_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform Essentials for Red Hat Technical Sales Partners")
    $cc2:CourseCompletion(this != $cc1, courseName == "RHN Satellite Sales")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "Red Hat Enterprise Linux 7 Implementation")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "Satellite (5) FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2015", "1-Aug-2015", $cc1, $cc2, $cc3, $cc4 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "19_Red Hat Sales Engineer Specialist - Platform_with_4_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform Essentials for Red Hat Technical Sales Partners")
    $cc2:CourseCompletion(this != $cc1, courseName == "RHN Satellite Sales")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "Red Hat Enterprise Linux 7 Implementation")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "Red Hat Satellite 6 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2015", "1-Aug-2015", $cc1, $cc2, $cc3, $cc4 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "20_Red Hat Sales Engineer Specialist - Platform_with_6_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform Solutions for PreSales")
    $cc2:CourseCompletion(this != $cc1, courseName == "RHEL 6 Sales Essentials Level 2")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "RHEL 6 Sales Essentials Add-ons")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "RHN Satellite Sales")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, courseName == "Red Hat Enterprise Linux 7 Implementation")
    $cc6:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, courseName == "Satellite (5) FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2015", "1-Aug-2015", $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "21_Red Hat Sales Engineer Specialist - Platform_with_6_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform Solutions for PreSales")
    $cc2:CourseCompletion(this != $cc1, courseName == "RHEL 6 Sales Essentials Level 2")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "RHEL 6 Sales Essentials Add-ons")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "RHN Satellite Sales")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, courseName == "Red Hat Enterprise Linux 7 Implementation")
    $cc6:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, courseName == "Red Hat Satellite 6 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2015", "1-Aug-2015", $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "22_Red Hat Sales Engineer Specialist - Platform_with_5_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform Essentials for Red Hat Technical Sales Partners")
    $cc2:CourseCompletion(this != $cc1, courseName == "RHN Satellite Sales")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "RHEL (6) Implementation")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "Red Hat Satellite 6 Implementation")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, courseName == "RHEL (6) Troubleshooting")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2015", "1-Aug-2015", $cc1, $cc2, $cc3, $cc4, $cc5 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "23_Red Hat Sales Engineer Specialist - Platform_with_7_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform Solutions for PreSales")
    $cc2:CourseCompletion(this != $cc1, courseName == "RHEL 6 Sales Essentials Level 2")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "RHEL 6 Sales Essentials Add-ons")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "RHN Satellite Sales")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, courseName == "RHEL (6) Implementation")
    $cc6:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, courseName == "RHEL (6) Troubleshooting")
    $cc7:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, this != $cc6, courseName == "Red Hat Satellite 6 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2015", "1-Aug-2015", $cc1, $cc2, $cc3, $cc4, $cc5, $cc6, $cc7 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5, $cc6, $cc7 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "24_Red Hat Sales Engineer Specialist - Platform_with_6_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform Solutions for PreSales")
    $cc2:CourseCompletion(this != $cc1, courseName == "RHEL 6 Sales Essentials Level 2")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "RHEL 6 Sales Essentials Add-ons")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "RHN Satellite Sales")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, courseName == "Red Hat Enterprise Linux 7 Implementation")
    $cc6:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, courseName == "Red Hat Satellite 6 FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Aug-2015", "", $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "25_Red Hat Sales Engineer Specialist - Platform_with_4_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform Essentials for Red Hat Technical Sales Partners")
    $cc2:CourseCompletion(this != $cc1, courseName == "RHN Satellite Sales")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "Red Hat Enterprise Linux 7 Implementation")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "Red Hat Satellite 6 FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Aug-2015", "", $cc1, $cc2, $cc3, $cc4 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "26_Red Hat Sales Engineer Specialist - Platform_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform Solutions for PreSales")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2012", "1-Jun-2013", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "27_Red Hat Sales Engineer Specialist - Platform Migration_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform Migration for Presales")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Aug-2013", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Platform Migration");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "28_Red Hat Sales Engineer Specialist - Storage_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Storage Solution for PreSales")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Nov-2012", "1-Aug-2013", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Storage");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "29_Red Hat Sales Engineer Specialist - Storage_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Storage Solution for PreSales")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat Gluster Storage 3 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Aug-2013", "1-Oct-2015", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Storage");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "30_Red Hat Sales Engineer Specialist - Storage_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Storage Solution for Salesperson")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat Gluster Storage 3 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Oct-2015", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Storage");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "31_Red Hat Sales Engineer Specialist - Storage_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Storage Solution for Salesperson")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat Ceph Storage FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2016", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Storage");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "32_Red Hat Sales Engineer Specialist - Virtualization_with_3_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "RHEV 3.1 for PreSales")
    $cc2:CourseCompletion(this != $cc1, courseName == "RHEV 3.1 Positioning and Pricing")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "Red Hat Enterprise Virtualization FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2013", "1-Jul-2014", $cc1, $cc2, $cc3))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Virtualization");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "33_Red Hat Sales Engineer Specialist - Virtualization_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "RHEV 3.1 for PreSales")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat Enterprise Virtualization FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jul-2014", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Virtualization");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "34_Red Hat Sales Specialist - Platform_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform 2.0 for Sales")
    $cc2:CourseCompletion(this != $cc1, courseName == "RHN Satellite Sales")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jul-2014", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "35_Red Hat Sales Specialist - Platform_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Sales Specialist - Platform")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2012", "1-Aug-2013", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "36_Red Hat Sales Specialist - Platform_with_4_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Sales Specialist - Platform")
    $cc2:CourseCompletion(this != $cc1, courseName == "RHEL 6 Sales Essentials Level 2")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "RHEL 6 Sales Essentials Add-ons")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "RHN Satellite Sales")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Aug-2013", "", $cc1, $cc2, $cc3, $cc4 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Specialist - Platform");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "37_Red Hat Sales Specialist - Platform Migration_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform Migration for Sales")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Aug-2013", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Specialist - Platform Migration");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "38_Red Hat Sales Specialist - Storage_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Storage Solution for Salesperson")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Oct-2013", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Specialist - Storage");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "39_Red Hat Sales Specialist - Virtualization_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Virtualization Solution for Salesperson")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2013", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Specialist - Virtualization");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "40_Red Hat Delivery Specialist - Automated SAP HANA System Replication with Pacemaker_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Automated SAP HANA System Replication with Pacemaker")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Apr-2016", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Automated SAP HANA System Replication with Pacemaker");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "41_Red Hat Delivery Specialist - System Z FASTRAX_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Systems FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Apr-2016", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - System Z FASTRAX");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "42_Red Hat Delivery Specialist - RHEL Atomic Host and Containers_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Enterprise Linux Atomic Host and Containers")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2015", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - RHEL Atomic Host and Containers");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end
