package com.redhat.gpe.accreditation.rules;

dialect "mvel"

import java.util.Date
import java.util.ArrayList
import com.redhat.gpe.domain.canonical.Student
import com.redhat.gpe.domain.canonical.StudentAccreditation
import com.redhat.gpe.domain.helper.CourseCompletion
import com.redhat.gpe.domain.helper.Accreditation
import com.redhat.gpte.util.DroolsCommandHelper

global ArrayList accreditationList



rule "4_Red Hat Sales Engineer Specialist - Cloud Management_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat CloudForms FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2014", "1-Jul-2014", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "5_Red Hat Sales Engineer Specialist - Cloud Management_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Cloud Management Solution for Sales Engineer  ")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat CloudForms FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jul-2014", "1-Aug-2016", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "6_Red Hat Sales Engineer Specialist - Cloud Management_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Cloud Management Solution for Sales Engineer  ")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat CloudForms 4 FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2016", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "7_Red Hat Delivery Specialist - Cloud Management_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat CloudForms FASTRAX")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat CloudForms Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2014", "1-Aug-2016", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "8_Red Hat Delivery Specialist - Cloud Management_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat CloudForms 4 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat CloudForms 4 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2016", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "9_Red Hat Sales Specialist - Cloud Management_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Cloud Management Solution for Salesperson")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jul-2014", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Specialist - Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "10_Red Hat Delivery Specialist - Advanced Cloud Management_with_5_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat CloudForms FASTRAX")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat CloudForms Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "Red Hat Satellite 6 Implementation")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "Red Hat CloudForms Customization & Automation")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, courseName == "Red Hat Cloud Suite FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2016", "", $cc1, $cc2, $cc3, $cc4, $cc5 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Advanced Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "11_Red Hat Delivery Specialist - Advanced Cloud Management_with_5_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat CloudForms 4 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat CloudForms 4 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "Red Hat Satellite 6 Implementation")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "Red Hat CloudForms 4 Customization & Automation")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, courseName == "Red Hat Cloud Suite FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2016", "", $cc1, $cc2, $cc3, $cc4, $cc5 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Advanced Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "12_Red Hat Advanced Delivery Specialist - Cloud Management_with_3_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat CloudForms FASTRAX")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat CloudForms Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "Red Hat CloudForms Customization & Automation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jun-2014", "1-Mar-2016", $cc1, $cc2, $cc3))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Advanced Delivery Specialist - Cloud Management");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "13_Red Hat Sales Engineer Specialist - Infrastructure as a Service_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat OpenStack Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2014", "1-Apr-2015", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "14_Red Hat Sales Engineer Specialist - Infrastructure as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat OpenStack for Sales")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat OpenStack 6 FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Apr-2015", "1-May-2016", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "15_Red Hat Sales Engineer Specialist - Infrastructure as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat OpenStack for Sales")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat OpenStack 7 FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Nov-2015", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "16_Red Hat Sales Engineer Specialist - Infrastructure as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat OpenStack for Sales")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat OpenStack 8 FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2016", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "17_Red Hat Delivery Specialist - Infrastructure as a Service_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat OpenStack Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2014", "1-Aug-2015", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "18_Red Hat Delivery Specialist - Infrastructure as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat OpenStack 6 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat OpenStack 6 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Aug-2015", "1-May-2016", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "19_Red Hat Delivery Specialist - Infrastructure as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat OpenStack 7 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat OpenStack 7 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Nov-2015", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "20_Red Hat Delivery Specialist - Infrastructure as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat OpenStack 8 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat OpenStack 8 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Feb-2016", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "21_Red Hat Sales Specialist - Infrastructure as a Service_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "IaaS Solutions for Salesperson")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jun-2014", "1-Apr-2015", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "22_Red Hat Sales Specialist - Infrastructure as a Service_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat OpenStack for Sales")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Apr-2015", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Specialist - Infrastructure as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "23_Red Hat Delivery Specialist - Advanced Cloud Infrastructure_with_6_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat OpenStack 7 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat OpenStack 7 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "Red Hat Ceph Storage for OpenStack")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "Installation and Continuous Deployment with Red Hat OpenStack Platform 8 Director")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, courseName == "Advanced Storage with Red Hat OpenStack")
    $cc6:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, courseName == "Advanced Networking with Red Hat OpenStack")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2016", "", $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Advanced Cloud Infrastructure");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");  
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "24_Red Hat Delivery Specialist - Advanced Cloud Infrastructure_with_6_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat OpenStack 8 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, courseName == "Red Hat OpenStack 8 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "Red Hat Ceph Storage for OpenStack")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "Installation and Continuous Deployment with Red Hat OpenStack Platform 8 Director")
    $cc5:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, courseName == "Advanced Storage with Red Hat OpenStack")
    $cc6:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, this != $cc4, this != $cc5, courseName == "Advanced Networking with Red Hat OpenStack")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2016", "", $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4, $cc5, $cc6 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Advanced Cloud Infrastructure");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");  
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "25_Red Hat Delivery Specialist - Red Hat Ceph for OpenStack_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Red Hat Ceph for OpenStack")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2016", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Red Hat Ceph for OpenStack");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "26_Red Hat Sales Engineer Specialist - Platform as a Service_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "OpenShift 2 Administration")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2014", "1-Jul-2014", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Platform as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "27_Red Hat Sales Engineer Specialist - Platform as a Service_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform as a Service Solution for Sales Engineer ")
    $cc2:CourseCompletion(this != $cc1, courseName == "OpenShift Administration")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jul-2014", "1-Jun-2016", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - Platform as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "28_Red Hat Sales Specialist - Platform as a Service_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform as a Service Solution for Salesperson")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jul-2014", "", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Specialist - Platform as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "29_Red Hat Delivery Specialist - Platform as a Service_with_1_course"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "OpenShift 2 Administration")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jan-2014", "1-Jun-2016", $cc1))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Platform as a Service");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "30_Red Hat Sales Engineer Specialist - DevOps_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "Platform as a Service Solution for Sales Engineer ")
    $cc2:CourseCompletion(this != $cc1, courseName == "OpenShift 3 FASTRAX")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jun-2015", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Sales Engineer Specialist - DevOps");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "31_Red Hat Delivery Specialist - DevOps_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "OpenShift Enterprise 3 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, courseName == "OpenShift Enterprise 3 Implementation")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Jun-2015", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - DevOps");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "32_Red Hat Delivery Specialist - DevOps_with_2_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "OpenShift Enterprise 3 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, courseName == "Application Development with OpenShift by Red Hat")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2016", "", $cc1, $cc2))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2);

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - DevOps");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end

rule "33_Red Hat Delivery Specialist - Advanced DevOps_with_4_courses"
when
    $student:Student()
    $cc1:CourseCompletion(courseName == "OpenShift Enterprise 3 FASTRAX")
    $cc2:CourseCompletion(this != $cc1, courseName == "OpenShift Enterprise 3 Implementation")
    $cc3:CourseCompletion(this != $cc1, this != $cc2, courseName == "Application Development with OpenShift by Red Hat")
    $cc4:CourseCompletion(this != $cc1, this != $cc2, this != $cc3, courseName == "Advanced Topics with OpenShift Enterprise 3 by Red Hat")
    eval(DroolsCommandHelper.isLatestCourseCompletionWithinDates(false, "1-Mar-2016", "", $cc1, $cc2, $cc3, $cc4 ))
then
    CourseCompletion latestCC = DroolsCommandHelper.determineMostRecentCourseCompletion(false, $cc1, $cc2, $cc3, $cc4 );

    Accreditation accreditation = new Accreditation();
    accreditation.setAccreditationName("Red Hat Delivery Specialist - Advanced DevOps");
    accreditation.setStudentId($student.getStudentid());
    accreditation.setEmail($student.getEmail());
    accreditation.setCourseId(latestCC.getCourseId());
    accreditation.setCourseName(latestCC.getCourseName());
    accreditation.setAccreditationDate(latestCC.getAssessmentDate());
    accreditation.setAccreditationType("Active");
    accreditation.setRuleFired(drools.getRule().getName());

    accreditationList.add(accreditation);
    System.out.println("   [ "+ $student.getEmail()+" : Fired: " + drools.getRule().getName() + " ]");
end
