---

- name: allow httpd connections to Apache Web Server
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: update /etc/httpd/conf.d/ssl.conf such that it is using GPTE self-signed cert and key
  lineinfile:
    dest: /etc/httpd/conf.d/ssl.conf
    regexp: '^SSLCertificateFile'
    line: 'SSLCertificateFile /etc/gpte/certs/gpteserver.crt'
- lineinfile:
    dest: /etc/httpd/conf.d/ssl.conf
    regexp: '^SSLCertificateKeyFile'
    line: 'SSLCertificateKeyFile /etc/gpte/certs/gpteserver.key'

- name: httpd configuration; create dashbuilder.conf
  template:
    src: dashbuilder.conf
    dest: /etc/httpd/conf.d

- name: httpd configuration; create gpte-reporting.conf
  template:
    src: generate_gpte_certs.sh
    dest: /tmp
    mode: 755
- shell: /tmp/generate_gpte_certs.sh
