---

- name: Install MariaDb and MySQL-python (so as to be able to use  "mysql_user" ansible module)
  yum: name=mariadb-server state=present
- yum: name=MySQL-python state=present

- name: Create installation directory
  file: path={{install_script_dir}}/{{mysql_install_script_dir}} state=directory mode=0755

- name: Copy my.cnf
  template:
    src: my.cnf
    dest: /etc 

- name : Copy installation files
  copy: src=install/ dest={{install_script_dir}}/{{mysql_install_script_dir}}

- name: Set file permissions
  file: 
    path={{install_script_dir}}/{{mysql_install_script_dir}}/{{item}} 
    mode=0775
  with_items:
    - run-mysqld.sh
    - scripts/common.sh

- name: Configure Mariadb
  shell: 
    '{{install_script_dir}}/{{mysql_install_script_dir}}/run-mysqld.sh >> {{install_script_dir}}/mysqld-install-log.txt
    creates={{install_script_dir}}/mysqld-install-log.txt'
  environment:
    MYSQL_ROOT_PASSWORD: "{{db_root_passwd}}"

- name: Start Mariadb
  service: name=mariadb state=started

- name: Enable Mariadb
  service: name=mariadb enabled=yes
