---

- name: Install mysql-connector-java
  yum: name=mysql-connector-java state=present

- name: Create installation target directory
  file: path={{mw_install_dir}} state=directory owner={{user}} group={{user}}

- name: Unarchive EAP distro if doesn't already exist
  stat: 
    path: "{{eap_home}}"
  register: st
- unarchive: src={{eap_distro}} dest={{mw_install_dir}} owner={{user}} group={{user}}
  when: st.stat.isdir is not defined

- name: Copy JBoss EAP cli scripts to target
  copy: src=templates/{{eap_generic_cli}} dest=/tmp owner={{user}} group={{user}}
- copy: src=templates/{{lms_trans_cli}} dest=/tmp owner={{user}} group={{user}}

- name: Search and replace variables in database CLI scripts
  replace: dest=/tmp/{{eap_generic_cli}} regexp='@@lms_trans_module_name@@' replace={{lms_trans_module_name}}
- replace: dest=/tmp/{{eap_generic_cli}} regexp='@@lms_trans_driver_jar_dir@@' replace={{lms_trans_driver_jar_dir}}
- replace: dest=/tmp/{{eap_generic_cli}} regexp='@@lms_trans_driver_jar@@' replace={{lms_trans_driver_jar}}
- replace: dest=/tmp/{{eap_generic_cli}} regexp='@@lms_trans_module_name@@' replace={{lms_trans_module_name}}
- replace: dest=/tmp/{{lms_trans_cli}} regexp='@@lms_trans_userId@@' replace={{lms_trans_userId}}
- replace: dest=/tmp/{{lms_trans_cli}} regexp='@@lms_trans_passwd@@' replace={{lms_trans_passwd}}

- name: Ensure JBoss EAP has correct JVM settings and binds to ports that do not conflict with dashbuilder
  replace: dest={{eap_home}}/bin/standalone.conf regexp='-Xms1303m -Xmx1303m' replace={{eap_jvm_props}}

- name: Add system properties to JBoss EAP
  blockinfile:
    dest: "{{eap_home}}/bin/standalone.conf"
    block: |
      JAVA_OPTS="$JAVA_OPTS -Dmysql.host.ip={{lms_trans_host_ip}}"
      JAVA_OPTS="$JAVA_OPTS -Dmysql.host.port={{lms_trans_host_port}}"
      JAVA_OPTS="$JAVA_OPTS -Dlms_trans_db_name={{lms_trans_db_name}}"
    
- name: Start EAP in admin mode and execute cli scripts
  stat: 
    path: "{{eap_home}}/modules/com/mysql"
  register: st
- command: "{{eap_home}}/bin/standalone.sh --admin-only"
  async:   15
  poll:    0
- command: "sleep 3"
- command: "{{eap_home}}/bin/jboss-cli.sh -c --controller=localhost:10124 --file=/tmp/{{lms_trans_cli}}"
- command: "{{eap_home}}/bin/jboss-cli.sh -c --controller=localhost:10124 --file=/tmp/{{eap_generic_cli}}"
  when: st.stat.isdir is not defined
- command: "{{eap_home}}/bin/jboss-cli.sh -c :shutdown"
  async:   5
  poll:    0
