---

#########       PRODUCT INSTALLS        ################
- name: Install mysql-connector-java
  yum: name=mysql-connector-java state=present

- name: Create installation target directory
  file: path={{mw_install_dir}} state=directory owner={{user}} group={{user}}

- name: Unarchive EAP distro if doesn't already exist
  stat: 
    path: "{{eap_home}}"
  register: st
- unarchive: src={{eap_distro}} dest={{mw_install_dir}} owner={{user}} group={{user}}
  when: st.stat.isdir is not defined

- name: Unarchive Fuse distro if doesn't already exist
  stat: 
    path: "{{eap_home}}/fusepatch"
  register: st
- copy: src={{fuse_eap_distro}} dest=/tmp
  when: st.stat.isdir is not defined
- shell: java -jar /tmp/{{fuse_eap_distro}}
  args:
      chdir: "{{eap_home}}"
  become: yes
  become_user: "{{user}}"
  when: st.stat.isdir is not defined

- name: delete * from {{eap_home}}/standalone/deployments
  shell: rm -rf {{eap_home}}/standalone/deployments/*




#########       GPTE Reporting Customizations to Fuse on EAP        ################
- name: Copy JBoss EAP cli scripts to target
  template: 
    src: "{{eap_generic_cli}}" 
    dest: /tmp 
    owner: "{{user}}"
    group: "{{user}}"
- template: 
    src: "{{lms_trans_cli}}" 
    dest: /tmp 
    owner: "{{user}}" 
    group: "{{user}}"

- name: Ensure JBoss EAP has correct JVM settings and binds to ports that do not conflict with dashbuilder
  replace: dest={{eap_home}}/bin/standalone.conf regexp='-Xms1303m -Xmx1303m' replace={{eap_jvm_props}}

- name: Add system properties to JBoss EAP
  blockinfile:
    dest: "{{eap_home}}/bin/standalone.conf"
    block: |
      JAVA_OPTS="$JAVA_OPTS -Dmysql.host.ip={{lms_trans_host_ip}}"
      JAVA_OPTS="$JAVA_OPTS -Dmysql.host.port={{lms_trans_host_port}}"
      JAVA_OPTS="$JAVA_OPTS -Dlms_trans_db_name={{lms_trans_db_name}}"
    
- name: Start EAP (as jboss user) in admin mode so as to be available for execution of CLI scripts
  stat: 
    path: "{{eap_home}}/modules/com/mysql"
  register: st
- command: "{{eap_home}}/bin/standalone.sh --admin-only"
  async:   15
  poll:    0
  become: yes
  become_user: "{{user}}"
- command: "sleep 3"

- name: Now that EAP is executing, run CLI scripts
  command: "{{eap_home}}/bin/jboss-cli.sh -c --controller=localhost:10124 --file=/tmp/{{lms_trans_cli}}"
- command: "{{eap_home}}/bin/jboss-cli.sh -c --controller=localhost:10124 --file=/tmp/{{eap_generic_cli}}"
  become: yes
  become_user: "{{user}}"
  when: st.stat.isdir is not defined
- command: "{{eap_home}}/bin/jboss-cli.sh -c :shutdown"
  async:   5
  poll:    0

