# Provisions the base components of GPTE Reporting that are not subject to change.
# End state of having executed this ansible script is a single machine with all GPTE Reporting base components enabled but stopped.

- hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: gpte_env
      prompt: "GPTE Reporting Environment (valid options:  prod, qa, dev) : "
      private: no

  # Appears that this now works: https://github.com/ansible/ansible/issues/10942
  # As of ansible v.2.1.2.0
  pre_tasks:
  - set_fact: gpte_env={{ gpte_env }}

  tasks:
  - debug: 
      msg: "Will install the following environment: {{ hostvars.localhost.gpte_env }}"

- hosts: "{{ hostvars['localhost']['gpte_env'] }}"
  remote_user: root

  pre_tasks:
  - set_fact: gpte_env={{ hostvars['localhost']['gpte_env'] }}

  roles:
#    - hostname
#    - os_update
#    - yum-clean
#    - firewalld
#    - selinux
#    - httpd
#    - reboot
#    - useradd
#    - opentlc-user
#    - tools
#    - java
#    - maven
#    - systemd
#    - mariadb
#    - mariadb-reporting-db
#    - eap
    - dashbuilder
#    - yum-clean
