# Responsible for syncing GPTE Reporting with OPEN/RHPDS utilization data.

- hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: gpte_env
      prompt: "GPTE Reporting Environment (valid options:  prod, qa, dev) : "
      private: no

# Appears that this now works: https://github.com/ansible/ansible/issues/10942
# As of ansible v.2.1.2.0
  pre_tasks:
    - set_fact: gpte_env={{ gpte_env }}
  
  tasks:
  - name: Add dev to dynamic inventory
    add_host:
      name: "{{dev}}"
      groups: gpte_dynamic
    when: gpte_env == "dev"

  - name: Add qa to dynamic inventory
    add_host:
      name: "{{qa}}"
      groups: gpte_dynamic
    when: gpte_env == "qa"

  - name: Add prod to dynamic inventory
    add_host:
      name: "{{prod}}"
      groups: gpte_dynamic
    when: gpte_env == "prod"
  

- hosts: gpte_dynamic
  remote_user: root

  pre_tasks:
    - set_fact: 
        gpte_env: "{{ hostvars['localhost']['gpte_env'] }}"
        prod_backup_only: false
    - debug:
        msg: "Will install the following environment: {{ hostvars.localhost.gpte_env }}"


  roles:

    - utilization_sync
