---

# Usage:  ansible-playbook utilization_sync.yml


- name: Create upload folder at  {{ database_update_script_dir }}
  file: path={{ database_update_script_dir }} state=directory
  run_once: true

- name: Copy utilization script
  template:
    src: utilization_sync.sh
    dest: "{{ database_update_script_dir }}"
    mode: 0755
    owner: "{{user}}"
    group: "{{user}}"

- name: Dump remote utilization databases (via psql utility)
  shell: "sh {{ database_update_script_dir }}/utilization_sync.sh {{item}}"
  with_items: "{{utilization_dbs}}"
