---


- name: Create upload folder at  {{ database_update_script_dir }}
  file: path={{ database_update_script_dir }} state=directory
  run_once: true

- name: Dump remote utilization databases
  postgresql_db:
    login_host: "{{ utilization_db_host }}"
    login_password: "{{ utilization_db_password }}"
    login_user: "{{ utilization_db_username  }}"
    name: "{{ item }}"
    state: dump
    target: "{{ database_update_script_dir }}/{{ item }}Db.sql.gz"
  with_items: "{{utilization_dbs}}"

