/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Feb 19 14:36:19 BRST 2016
 */
package com.redhat.gpe.domain.integration.salesforce;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist DeviceFormat
 */
public enum DeviceFormatEnum {

    // Aloha
    ALOHA("Aloha"),
    // Desktop
    DESKTOP("Desktop"),
    // Phone
    PHONE("Phone"),
    // Tablet
    TABLET("Tablet");

    final String value;

    private DeviceFormatEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static DeviceFormatEnum fromValue(String value) {
        for (DeviceFormatEnum e : DeviceFormatEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
