/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Feb 19 14:36:19 BRST 2016
 */
package com.redhat.gpe.domain.integration.salesforce;

import com.thoughtworks.xstream.annotations.XStreamAlias;
import org.apache.camel.component.salesforce.api.dto.AbstractSObjectBase;
import org.codehaus.jackson.annotate.JsonProperty;

/**
 * Salesforce DTO for SObject GrantedByLicense
 */
@XStreamAlias("GrantedByLicense")
public class GrantedByLicense extends AbstractSObjectBase {

    // PermissionSetLicenseId
    private String PermissionSetLicenseId;

    @JsonProperty("PermissionSetLicenseId")
    public String getPermissionSetLicenseId() {
        return this.PermissionSetLicenseId;
    }

    @JsonProperty("PermissionSetLicenseId")
    public void setPermissionSetLicenseId(String PermissionSetLicenseId) {
        this.PermissionSetLicenseId = PermissionSetLicenseId;
    }

    // CustomPermissionId
    private String CustomPermissionId;

    @JsonProperty("CustomPermissionId")
    public String getCustomPermissionId() {
        return this.CustomPermissionId;
    }

    @JsonProperty("CustomPermissionId")
    public void setCustomPermissionId(String CustomPermissionId) {
        this.CustomPermissionId = CustomPermissionId;
    }

}
