/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Feb 19 14:36:19 BRST 2016
 */
package com.redhat.gpe.domain.integration.salesforce;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist ImportExportAgent
 */
public enum ImportExportAgentEnum {

    // A
    A("A"),
    // B
    B("B"),
    // C
    C("C"),
    // D
    D("D"),
    // E
    E("E"),
    // F
    F("F"),
    // G
    G("G"),
    // H
    H("H");

    final String value;

    private ImportExportAgentEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static ImportExportAgentEnum fromValue(String value) {
        for (ImportExportAgentEnum e : ImportExportAgentEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
