/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Feb 19 14:36:19 BRST 2016
 */
package com.redhat.gpe.domain.integration.salesforce;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist MobileSessionTimeout
 */
public enum MobileSessionTimeoutEnum {

    // 1
    _1("1"),
    // 10
    _10("10"),
    // 120
    _120("120"),
    // 180
    _180("180"),
    // 240
    _240("240"),
    // 30
    _30("30"),
    // 5
    _5("5"),
    // 60
    _60("60");

    final String value;

    private MobileSessionTimeoutEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static MobileSessionTimeoutEnum fromValue(String value) {
        for (MobileSessionTimeoutEnum e : MobileSessionTimeoutEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
