/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Feb 19 14:36:19 BRST 2016
 */
package com.redhat.gpe.domain.integration.salesforce;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist RuleStatus
 */
public enum RuleStatusEnum {

    // Activating
    ACTIVATING("Activating"),
    // ActivationFailed
    ACTIVATIONFAILED("ActivationFailed"),
    // Active
    ACTIVE("Active"),
    // Deactivating
    DEACTIVATING("Deactivating"),
    // DeactivationFailed
    DEACTIVATIONFAILED("DeactivationFailed"),
    // Inactive
    INACTIVE("Inactive");

    final String value;

    private RuleStatusEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static RuleStatusEnum fromValue(String value) {
        for (RuleStatusEnum e : RuleStatusEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
