/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Feb 19 14:36:19 BRST 2016
 */
package com.redhat.gpe.domain.integration.salesforce;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist SessionSecurityLevel
 */
public enum SessionSecurityLevelEnum {

    // HIGH_ASSURANCE
    HIGH_ASSURANCE("HIGH_ASSURANCE"),
    // LOW
    LOW("LOW"),
    // STANDARD
    STANDARD("STANDARD");

    final String value;

    private SessionSecurityLevelEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static SessionSecurityLevelEnum fromValue(String value) {
        for (SessionSecurityLevelEnum e : SessionSecurityLevelEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
