/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 * Generated on: Fri Feb 19 14:36:19 BRST 2016
 */
package com.redhat.gpe.domain.integration.salesforce;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist UiSkin
 */
public enum UiSkinEnum {

    // PortalDefault
    PORTALDEFAULT("PortalDefault"),
    // Theme1
    THEME1("Theme1"),
    // Theme2
    THEME2("Theme2"),
    // Theme3
    THEME3("Theme3"),
    // Theme4d
    THEME4D("Theme4d"),
    // Webstore
    WEBSTORE("Webstore");

    final String value;

    private UiSkinEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static UiSkinEnum fromValue(String value) {
        for (UiSkinEnum e : UiSkinEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }

}
