---

- name: Unarchive Maven distro if doesn't already exist
  stat:
    path: "{{mvn_install_dir}}/{{mvn_root}}"
  register: st
- unarchive: src={{mvn_distro}} dest={{mvn_install_dir}} owner={{user}} group={{user}}
  when: st.stat.isdir is not defined
