---

- name: Create installation target directory
  file: path={{rhsso_install_dir}} state=directory owner={{user}} group={{user}}

- name: Create rhsso installation directory
  file: path={{install_script_dir}}/{{rhsso_install_script_dir}} state=directory mode=0755

- name : Copy installation script
  template: src={{item}} dest={{install_script_dir}}/{{rhsso_install_script_dir}}
  with_items:
    - install/{{rhsso_install_script}}

- name: Create rhsso configuration directory
  file: path={{install_script_dir}}/{{rhsso_install_script_dir}}/{{rhsso_configuration_dir}} state=directory mode=0755

- name : Copy configuration files
  copy: src={{item}} dest={{install_script_dir}}/{{rhsso_install_script_dir}}//{{rhsso_configuration_dir}} mode=0755
  with_items:
    - configuration/keycloak-add-user.json

- name: Copy configuration templates
  template: src={{item}} dest={{install_script_dir}}/{{rhsso_install_script_dir}}//{{rhsso_configuration_dir}} mode=0755
  with_items:
    - configuration/rhsso.cli
    - configuration/rhsso-mysql.sql

- name: Create installation resources directory
  file: path={{install_script_dir}}/{{rhsso_install_script_dir}}/{{rhsso_resources_dir}} state=directory mode=0755

- name: Copy RH-SSO distro
  copy: src={{rhsso_distro}} dest={{install_script_dir}}/{{rhsso_install_script_dir}}/{{rhsso_resources_dir}}/{{rhsso_distro}}

- name: Set file permissions
  file: 
    path={{install_script_dir}}/{{rhsso_install_script_dir}}/{{item}}
    mode=0775
  with_items:
    - "{{rhsso_install_script}}"

- name: Copy installation script template
  template: src={{item}}  dest={{lab_home_dir}} owner={{user}} group={{user}} mode=0755
  with_items:
    - install/install-rhsso.sh