---

# GPTE Reporting database backup from prod


- name: Create Backups folder on prod
  file: path={{ prod_dump_dir }} state=directory
  run_once: true
  delegate_to: reporting.opentlc.com

- name: Dump remote prod databases
  mysql_db: 
    login_user: root
    login_host: localhost
    login_password: "{{ db_root_passwd }}"
    name: "{{ item }}"
    state: dump 
    target: "{{ prod_dump_dir }}/{{ item }}Db.sql.gz"
  with_items: databases_to_update
  delegate_to: reporting.opentlc.com

- name: Create following directory from which to put fetched database zips; local:{{target_bk_dir}}
  command: mkdir -p {{ target_bk_dir }}
  delegate_to: localhost

- name: Copy database dump files from prod to local:{{target_bk_dir}}
  fetch:
    src: "{{ prod_dump_dir }}/{{ item }}Db.sql.gz"
    dest: "{{ target_bk_dir }}"
    flat: yes
  with_items: databases_to_update
  delegate_to: reporting.opentlc.com

- name: Create Backups folder on remote {{gpte_env}} environment
  file: path={{ target_bk_dir }} state=directory

- name: push database dump files from local to remote {{gpte_env}} environment
  copy:
    src: "{{ target_bk_dir }}/{{ item }}Db.sql.gz"
    dest: "{{ target_bk_dir }}"
  with_items: databases_to_update

- name: import data into {{gpte_env}} RDBMS
  mysql_db:
    #login_user: root
    #login_host: localhost
    #login_password: "{{ db_root_passwd }}"
    name: "{{ item }}"
    state: import 
    target: "{{ target_bk_dir }}/{{ item }}Db.sql.gz"
  with_items: databases_to_update
  
