---

- name: Set environment variables and aliases for all users
  blockinfile:
    dest: /etc/bashrc
    block: |
        PATH=$PATH:/opt/apache-maven-3.2.5/bin

        # Git Completion: RHEL 7
        source /usr/share/git-core/contrib/completion/git-prompt.sh
        GIT_COMPLETION_PATH="/etc/bash_completion.d/git"
        if [ -f "$GIT_COMPLETION_PATH" ]; then
            GIT_PS1_SHOWDIRTYSTATE=true
            . "$GIT_COMPLETION_PATH"
            ADD_PS1='$(__git_ps1)'
        fi

        if [[ ${EUID} == 0 ]] ; then
            PS1="\[\033[01;31m\]\h\[\033[01;34m\] \w\[\033[33m\]$ADD_PS1\[\033[34m\] \$\[\033[00m\] "
        else
            PS1="\[\033[01;32m\]\u@\h\[\033[01;34m\] \w\[\033[33m\]$ADD_PS1\[\033[34m\] \$\[\033[00m\] "
        fi

        # GPTE Reporting convenience aliases
        alias bg='sudo systemctl restart gpte-integration.service'
        alias ba='sudo systemctl restart accred-process.service'
        alias bd='sudo systemctl restart dashbuilder.service'
        alias bduf='sudo systemctl restart dashbuilderuf.service'
        alias tg='sudo journalctl -u gpte-integration -f'
        alias ta='sudo journalctl -u accred-process -f'
        alias td='sudo journalctl -u dashbuilder -f'
        alias tduf='sudo journalctl -u dashbuilderuf -f'
        alias mroot='mysql -u root'

- name: Add jboss user
  user: name={{user}} groups=wheel password={{password}}

- name: Set environment variables for jboss user
  template: src=bashrc dest=/home/{{user}}/.bashrc owner={{user}} group={{group}}

- name: Ensure /opt directory is owned by jboss:jboss
  file: state=directory path=/opt owner={{user}} group={{group}}

- name: Create {{gpte_reporting_file_system}} directory and have it owned by jboss:jboss
  file:
    state: directory
    dest:  "{{gpte_reporting_file_system}}"
    owner: "{{user}}"
    group: "{{group}}"
