---

# NOTE: systemd ansible module is only available in version 2.2
#       As of 21 Dec, F25 only includes ansible 2.1.2

- name: Create and enable systemd config for dashbuilder
  template:
    src: dashbuilder.service
    dest: /usr/lib/systemd/system/
    mode: "u=rw,g=r,o=r"
- command: systemctl enable dashbuilder.service

- name: Create and enable systemd config for accred-process 
  template: 
    src: accred-process.service
    dest: /usr/lib/systemd/system/
    mode: "u=rw,g=r,o=r"
- command: systemctl enable accred-process.service

- name: Create and enable systemd config for gpte-integration
  template: 
    src: gpte-integration.service
    dest: /usr/lib/systemd/system/
    mode: "u=rw,g=r,o=r"
- command: systemctl enable gpte-integration.service

- name: enable systemd config for Apache Web Server
  command: systemctl enable httpd.service

- name: start systemd config for Apache Web Server
  command: systemctl start httpd.service
