:uri:
:toc: manual
:toc-placement: preamble
:numbered:
:rulesspreadsheet: link:https://docs.google.com/spreadsheets/d/1C4jbSADmHJvLL3PBBBSEB54L8G_I6NN5rblWIGymAXg/edit#gid=1640119171[GPTE Accreditation Rules Spreadsheet with validation]
:designdoc: link:https://docs.google.com/document/d/1rFioqj5uhLtdoUEfHHBEwh4_-bW7vqEc5N0R24tN9FU/edit#[GPTE Reporting design document]

= RHPDS/OPENTLC Reporting

== Overview
The Red Hat GPTE team has a need to provide reports regarding RHPDS/OPENTLC utilization by both Red Hat associates as well as Red Hat partners.

This data resides in a PGSQL database server.  The creation of a RESTful client that periodically pulls from Ravello and persists to a reporting database would be ideal.

A reporting database and a new Dashbuilder workspace/page should be created to report this information.

== Data Sources

=== Overview
GPTE Reporting will use the following databases as data sources for this effort.

=== Resources

===== _OPENTLC DB_

host=www00.opentlc.com

dbname=openusage

user=reportuser

password=fargnots!

sslmode=require


===== _RHPDS_

host=www00.opentlc.com

dbname=rhpdsusage

user=reportuser

password=fargnots!

sslmode=require

== Database Schema
The following is the current schema of the source database.

timestamp, 'userName', 'catalogItem', 'partner', 'blueprint', 'className', 'fullName', 'email', 'geo'


ifdef::showscript[]
endif::showscript[]
