# hosts
#prod: reporting.opentlc.com
#qa: qa.opentlc.com
#dev: dev.opentlc.com

prod: apps-iad01.opentlc.com
qa: qa-sfo00.opentlc.com
dev: gptebuild.opentlc.com


# Product artifacts
eap_distro: jboss-eap-6.4.6-full-build.zip
wildfly_distro: wildfly-8.2.0.Final.tar.gz
dashbuilder_distro: dashbuilder-6.3.0.Final-wildfly8.war
fuse_eap_distro: fuse-eap-installer-6.2.1.redhat-084.jar
mvn_root: apache-maven-3.2.5

# Operating system user and group
user: jboss
group: jboss

# Installation paths
mw_install_dir: /opt/jboss
eap_home: "{{mw_install_dir}}/jboss-eap-6.4"
wf_home: "{{mw_install_dir}}/wildfly-8.2.0.Final"
gpte_reporting_home: /opt/OPEN_Reporting
dashbuilder_customization_home: "{{gpte_reporting_home}}/reporting/dashbuilder_customizations/original/"
dashbuilder_runtime_artifact: "{{wf_home}}/standalone/deployments/dashbuilder.war"
install_script_dir: /opt/install/scripts

# General Database properties
db_root_passwd: c-9XSHln8hJ_UH9YvNOgc9mH

MYSQL_DATADIR: /var/lib/mysql
MYSQL_LOWER_CASE_TABLE_NAMES: 0
MYSQL_MAX_CONNECTIONS: 151
MYSQL_FT_MIN_WORD_LEN: 4
MYSQL_FT_MAX_WORD_LEN: 20
MYSQL_AIO: 1


# lms_trans database properties
lms_trans_module_name: com.mysql
lms_trans_driver_jar_dir: /usr/share/java
lms_trans_driver_jar: mysql-connector-java.jar
lms_trans_host_ip: localhost
lms_trans_host_port: 3306
lms_trans_db_name: lms_transactional
lms_trans_userId: lms
lms_trans_passwd: S7K_3KVyD7co4F-qSj_-Yl9Q

# lms_reporting database properties
lms_reporting_module_name: com.mysql
lms_reporting_driver_jar_dir: /usr/share/java
lms_reporting_driver_jar: mysql-connector-java.jar
lms_reporting_host_ip: localhost
lms_reporting_host_port: 3306
lms_reporting_db_name: lms_reporting
lms_reporting_userId: lms_report
lms_reporting_passwd: S7K_3KVyD7co4F-qSj_-Yl9Q

# dashbuilder database properties
dashbuilder_db_module_name: com.mysql
dashbuilder_db_driver_jar_dir: /usr/share/java
dashbuilder_db_driver_jar: mysql-connector-java.jar
dashbuilder_db_host_ip: localhost
dashbuilder_db_host_port: 3306
dashbuilder_db_name: dashbuilder
dashbuilder_db_userId: dashbuilder
dashbuilder_db_passwd: S7K_3KVyD7co4F-qSj_-Yl9Q

# The following property is only used during initial provisioning of a new GPTE Reporting environment
databases_to_provision_from_prod:
  - "{{ lms_trans_db_name }}"
  - "{{ dashbuilder_db_name }}"
  - "{{ lms_reporting_db_name }}"

# The following property is used when updating an environment that has been previously provisioned
# LMS Reporting should be updated in dev from prod because there are tables in that database that are NOT created from the stored procedures.
databases_to_update_from_prod:
  - "{{ lms_trans_db_name }}"
  - "{{ lms_reporting_db_name }}"

# The following property is used when updating production or qa database from dev
databases_to_update_from_dev:
  - "{{ dashbuilder_db_name }}"

mysql_datadump_src_dir: /tmp/mysqlbackup
mysql_datadump_target_dir: /tmp/mysqlbackup_target/
database_update_script_dir: /tmp/gpte/databaseUpdates

# GPTE Reporting parameters
gpte_domain_jar: gpte-domain-1.0.jar
course_completion_war: course-completion-process-1.0.war
student_reg_war: student-registration-process-1.0.war
shared_process_war: gpte-shared-process-1.0.war

# epel
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"

# GPTE self-signed certs
gpte_self_signed_certs_dir: "/etc/gpte/certs/"

# GPTE Reporting file system
gpte_reporting_file_system: /u01/gpte

# GPTE Accreditation Service
accred_process_log_dir: /var/log/gpte

# postfix mail relay settings
mail_relay_host: mx00.opentlc.com
mail_relay_port: 19587

# totara shadow db settings
totara_shadow_db_module_name: org.postgresql
totara_shadow_db_driver_jar_dir: /usr/share/java
totara_shadow_db_driver_jar: postgresql-jdbc.jar
totara_shadow_host_ip: 23.253.23.27
totara_shadow_host_port: 5432
totara_shadow_db_name: totara_redhat_reporting
totara_shadow_db_username: totara_redhat_reporting
totara_shadow_db_password: 87IW1o1zWff94CUXm+5w

# labs_demos_reporting db settings
labs_demos_reporting_db_module_name: org.postgresql
labs_demos_reporting_db_driver_jar_dir: /usr/share/java
labs_demos_reporting_db_driver_jar: postgresql-jdbc.jar
labs_demos_reporting_host_ip: www00.opentlc.com
labs_demos_reporting_host_port: 5432
labs_demos_reporting_db_name: openusage
labs_demos_reporting_db_userId: reportuser
labs_demos_reporting_db_passwd: fargnots!

path_to_swagger_ui: /opt/swagger-ui/

# OPEN/RHPDS Financial and Usage Data
open_rhpds_usage_db_module_name: org.postgresql
open_rhpds_usage_db_driver_jar_dir: /usr/share/java
open_rhpds_usage_driver_jar: postgresql-jdbc.jar
open_rhpds_usage_host_ip: www00.opentlc.com
open_rhpds_usage_host_port: 5432
open_rhpds_usage_username: reportuser
open_rhpds_usage_password: fargnots!
open_usage_db_name: openusage
rhpds_usage_db_name: rhpdsusage
