# Product artifacts
eap_distro: jboss-eap-6.4.6-full-build.zip
wildfly_distro: wildfly-8.2.0.Final.tar.gz
dashbuilder_distro: dashbuilder-6.3.0.Final-wildfly8.war
fuse_eap_distro: fuse-eap-installer-6.2.1.redhat-084.jar
mvn_root: apache-maven-3.2.5

# Operating system user and group
user: jboss
group: jboss

# Installation paths
mw_install_dir: /opt/jboss
eap_home: "{{mw_install_dir}}/jboss-eap-6.4"
wf_home: "{{mw_install_dir}}/wildfly-8.2.0.Final"
gpte_reporting_home: /opt/OPEN_Reporting
dashbuilder_customization_home: "{{gpte_reporting_home}}/reporting/dashbuilder_customizations/original/"
dashbuilder_runtime_artifact: "{{wf_home}}/standalone/deployments/dashbuilder.war"
install_script_dir: /opt/install/scripts

# General Database properties
db_root_passwd: c-9XSHln8hJ_UH9YvNOgc9mH

# lms_trans database properties
lms_trans_module_name: com.mysql
lms_trans_driver_jar_dir: /usr/share/java
lms_trans_driver_jar: mysql-connector-java.jar
lms_trans_host_ip: localhost
lms_trans_host_port: 3306
lms_trans_db_name: lms_transactional
lms_trans_userId: lms
lms_trans_passwd: S7K_3KVyD7co4F-qSj_-Yl9Q

# lms_reporting database properties
lms_reporting_module_name: com.mysql
lms_reporting_driver_jar_dir: /usr/share/java
lms_reporting_driver_jar: mysql-connector-java.jar
lms_reporting_host_ip: localhost
lms_reporting_host_port: 3306
lms_reporting_db_name: lms_reporting
lms_reporting_userId: lms_report
lms_reporting_passwd: S7K_3KVyD7co4F-qSj_-Yl9Q

# dashbuilder database properties
dashbuilder_db_module_name: com.mysql
dashbuilder_db_driver_jar_dir: /usr/share/java
dashbuilder_db_driver_jar: mysql-connector-java.jar
dashbuilder_db_host_ip: localhost
dashbuilder_db_host_port: 3306
dashbuilder_db_name: dashbuilder
dashbuilder_db_userId: dashbuilder
dashbuilder_db_passwd: S7K_3KVyD7co4F-qSj_-Yl9Q

# The following property is only used during initial provisioning of a new GPTE Reporting environment
databases_to_provision_from_prod:
  - "{{ lms_trans_db_name }}"
  - "{{ dashbuilder_db_name }}"
  - "{{ lms_reporting_db_name }}"

# The following property is used when updating an environment that has been previously provisioned
databases_to_update_from_prod:
  - "{{ lms_trans_db_name }}"

# The following property is used when updating production or qa database from dev
databases_to_update_from_dev:
  - "{{ dashbuilder_db_name }}"

src_dump_dir: /tmp/mysqlbackup
target_bk_dir: /tmp/mysqlbackup_target/


# GPTE Reporting parameters
gpte_domain_jar: gpte-domain-1.0.jar
course_completion_war: course-completion-process-1.0.war
student_reg_war: student-registration-process-1.0.war
shared_process_war: gpte-shared-process-1.0.war

# epel
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"
